# Generated by Django 4.1.13 on 2024-04-09 13:41

from django.db import migrations
import placard.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('placard', '0002_alter_projects_project_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountgroup',
            name='group_identifier',
            field=placard.models.StringUUIDField(blank=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='user_identifier',
            field=placard.models.StringUUIDField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accreditation',
            name='accreditation_identifier',
            field=placard.models.StringUUIDField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='grouprole',
            name='role_identifier',
            field=placard.models.StringUUIDField(default=uuid.uuid4, editable=False, max_length=36),
        ),
        migrations.AlterField(
            model_name='hierarchy',
            name='hierachy_identifier',
            field=placard.models.StringUUIDField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='hierarchyitem',
            name='HieraItem_identifier',
            field=placard.models.StringUUIDField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_identifier',
            field=placard.models.StringUUIDField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
