# Generated by Django 4.1.13 on 2024-04-09 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('placard', '0003_alter_accountgroup_group_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchy',
            name='hierachy_identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
