# Generated by Django 4.1.13 on 2024-04-09 13:46

from django.db import migrations
import placard.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('placard', '0004_alter_hierarchy_hierachy_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchy',
            name='hierachy_identifier',
            field=placard.models.StringUUIDField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
